services:
  # PHP-FPM (процессор PHP)
  php-nginx-tcp:
    build:
      context: ./docker
      dockerfile: php.Dockerfile
    container_name: php-nginx-tcp
    restart: unless-stopped
    env_file:
      - env/.env
    volumes:
      - ./public:/var/www/html
      - ./config/php/php.ini:/usr/local/etc/php/conf.d/local.ini:ro
    networks:
      - php-nginx-tcp-network
    healthcheck:
      test: [ "CMD", "cgi-fcgi", "-bind", "-connect", "localhost:9000" ]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s

  # Nginx Web Server (веб-сервер)
  nginx-tcp:
    image: nginx:alpine
    container_name: nginx-tcp
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www/html
      - ./config/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - php-nginx-tcp-network
    healthcheck:
      test: [ "CMD", "wget", "-q", "-O", "-", "http://localhost/" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      php-nginx-tcp:
        condition: service_healthy

  # PostgreSQL 17 (база данных)
  postgres-nginx-tcp:
    image: postgres:17
    container_name: postgres-nginx-tcp
    restart: unless-stopped
    env_file:
      - env/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - php-nginx-tcp-network
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  # pgAdmin 4 (Web UI для PostgreSQL)
  pgadmin-nginx-tcp:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    env_file:
      - env/.env
    ports:
      - "8080:80"
    depends_on:
      postgres-nginx-tcp:
        condition: service_healthy
    networks:
      - php-nginx-tcp-network
    healthcheck:
      test: [ "CMD", "wget", "-q", "-O", "-", "http://localhost/" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres-data:

networks:
  php-nginx-tcp-network:
    driver: bridge
